### ISSUE TITLE
Add UTF-8 support

### ISSUE THREAD

**Issue by 64** [Bfgeshka/termix#20]
How are we going to do this? We could roll our own but I think using something like [ICU](http://site.icu-project.org/) would be good.

**Comment by desolt** [comment]
I have very little knowledge in regards to encoding other than how it kind of works, so using something like @64 suggested would be helpful to me. If someone would like to implement their own solution that's fine too.

**Comment by Bfgeshka** [comment]
ICU is pretty big and that's something we wont use here.

**Comment by 64** [comment]
Then we'll need to find a smaller library or roll our own. Is anyone up for doing that? I personally don't have much experience with UTF-8.

**Comment by desolt** [comment]
Not experienced on encoding either, that leaves @Bfgeshka or someone who wants to join in with a solution, or we need to find a smaller library.
